use_frameworks!

platform :ios, '9.0'

target 'DFJellyAnimationView_Example' do
  pod 'DFJellyAnimationView', :path => '../'

  target 'DFJellyAnimationView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
